### PR TITLE
Geometry interfaces instead JTS

### PR DESCRIPTION
**Pull request by shruda**
Implement geometry interfaces to remove direct reference to JTS

### CODE REVIEW

**Comment by nicolas-f** [comment]
Hi,

I will look into it next week..

Thanks

++

**Comment by shruda** [comment]
thanks ;-) my next step is to adapt H2GIS. I will inform you if my branch/fork is ready.

**Comment by nicolas-f** [comment]
Hi,

I'm working on your patch in order to not have to use IGeometry in all H2GIS functions.

**Comment by shruda** [comment]
That sounds good. What's your plan to avoid that?

**Comment by nicolas-f** [comment]
I will define a method in order to know if a GeometryFactory can convert an object into a IGeometry and if yes create the ValueGeometry.

**Comment by nicolas-f** [comment]
I think it will be better if ValueGeometry is an abstract class and GeometryFactory provides an implementation. It would create twice less objects for a geometry field. What do you think ?

**Comment by shruda** [comment]
Maybe you are right, that would reduce a lot of lines of code.
Do you want do implement that or should I try this in a new branch?

**Comment by nicolas-f** [comment]
Ok If you agree I will make a proposal in the current pull request with additional commits.

**Comment by shruda** [comment]
Ok I agree ;-)

**Comment by shruda** [comment]
Hi nicolas,
I created a new branch to show you my idea/implementation of the abstract ValueGeometry.

https://github.com/shruda/H2-Mirror/tree/AbstractValueGeometry

I only had to change 7 files (mostly test classes )and add one new file to H2GIS. Only ST_MakeGrid, STMakeGridPoints and ST_MakePolygon had to be changed.

https://github.com/shruda/H2GIS/tree/AbstractValueGeometry

What do you think about this proposal?

**Comment by nicolas-f** [comment]
Hi,
It seems OK. There is minimal change in unit test. I will run unit tests.

regards,
Nicolas

**Comment by nicolas-f** [comment]
I have this errors when running build.sh

```
src/main/org/h2/value/Value.java:187: error: inconvertible types
                        (Class<? extends IValueGeometryFactory<?,?>>)IValueGeometryFactory.class);
                                                                                          ^
  required: Class<? extends IValueGeometryFactory<?,?>>
  found:    Class<IValueGeometryFactory>
src/main/org/h2/store/Data.java:776: error: cannot find symbol
            return ValueGeometry.get(b);
                                ^
  symbol:   method get(byte[])
  location: class ValueGeometry
src/main/org/h2/index/IndexCursor.java:191: warning: [unchecked] unchecked call to getEnvelopeUnion(ValueGeometry<T>) as a member of the raw type ValueGeometry
                    getEnvelopeUnion(vg);
                                    ^
  where T is a type-variable:
    T extends Object declared in class ValueGeometry
src/main/org/h2/expression/Comparison.java:298: warning: [unchecked] unchecked call to intersectsBoundingBox(ValueGeometry<T>) as a member of the raw type ValueGeometry
            result = lg.intersectsBoundingBox(rg);
                                             ^
  where T is a type-variable:
    T extends Object declared in class ValueGeometry
2 errors
2 warnings
Exception in thread "main" java.lang.RuntimeException: An error occurred
        at org.h2.build.BuildBase.javac(BuildBase.java:882)
        at org.h2.build.Build.compile(Build.java:219)
        at org.h2.build.Build.compile(Build.java:97)
        at org.h2.build.Build.jar(Build.java:395)
        at org.h2.build.Build.mavenInstallLocal(Build.java:719)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.h2.build.BuildBase.invoke(BuildBase.java:243)
        at org.h2.build.BuildBase.runTarget(BuildBase.java:208)
        at org.h2.build.BuildBase.run(BuildBase.java:189)
        at org.h2.build.Build.main(Build.java:34)

```

**Comment by shruda** [comment]
which java version do you use?
The execution of ...\H2-Mirror\h2\build.bat was successful on my machine. I was running the test by using jdk1.7.0_67 with 1.6 compiler compliance level - I think this could be the problem.

**Comment by nicolas-f** [comment]
I'm using java 1.6 and branch AbstractValueGeometry

``` sh
> java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
```

**Comment by shruda** [comment]
Ok, I will download this version and try to fix your mentioned problems.

**Comment by nicolas-f** [comment]
use this build command:

``` shell
sh build.sh mavenInstallLocal
```

**Comment by shruda** [comment]
Hi nicolas, sorry for the late response.
I pushed the fix for that problem. The only exception which occurs now is during the help generation. The org.h2.build.doc.GenerateHelp can't find the vividsolutions dependency and throws a NoClassDefFoundError.

Best Regards,
Steve

**Pull request merged**
